-- 1
CREATE TABLE MY_EMP (
	EMP_NUM INT PRIMARY KEY
	, EMP_NAME VARCHAR(20) NOT NULL
	, DEPT_NUM INT NOT NULL
	, DEPT_NAME VARCHAR(20) NOT NULL
	, JOB VARCHAR(20) NOT NULL
);

-- 2
INSERT INTO MY_EMP () VALUES (1, '지선영', 1, '백엔드반', '사장');
DELETE FROM my_emp;

-- 3
UPDATE my_emp SET EMP_NAME = '김자바', JOB = '대리' WHERE EMP_NUM = 1;

-- 4
SELECT
	EMPNO, ENAME, SAL, COMM
	FROM emp
	WHERE (SAL <= 500 OR SAL >= 1500)
	AND (COMM IS NOT NULL);
	
-- 5
SELECT
	EMPNO, ENAME, HIREDATE
	FROM EMP
	WHERE ENAME LIKE '이__'
	ORDER BY EMPNO ASC;
	
-- 6 (다시 확인)
SELECT
	EMPNO, ENAME, EMP.DEPTNO, DNAME
	, CASE
      WHEN EMP.DEPTNO=10 THEN '인사부'
      WHEN EMP.DEPTNO=20 THEN '영업부'
      ELSE '생산부'
      END
	FROM EMP
	INNER JOIN DEPT
	ON emp.DEPTNO = dept.DEPTNO
	
	