-- 1
CREATE TABLE MY_MEMBER (
	MEMBER_NUM INT PRIMARY KEY
	, MEMBER_ID VARCHAR(20) NOT NULL
	, MEMBER_PW VARCHAR(20) NOT NULL
	, MEMBER_NAME VARCHAR(20) NOT NULL
	, MEMBER_AGE INT
	, MEMBER_EMAIL VARCHAR(50)
);

-- 2
INSERT INTO MY_MEMBER(
	MEMBER_NUM
	, MEMBER_ID
	, MEMBER_PW
	, MEMBER_NAME
	, MEMBER_AGE
	, MEMBER_EMAIL
) VALUES (
	1
	, 'admin'
	, 'admin1234'
	, '관리자'
	, 25
	, 'admin@gmail.com'
);

DELETE FROM MY_MEMBER;

-- 3
UPDATE MY_MEMBER SET
	MEMBER_NAME = '김자바'
	, MEMBER_ID = 'KIMJAVA'
WHERE MEMBER_NUM = 1;

-- 4
SELECT
	EMPNO, ENAME, SAL, COMM
FROM emp
WHERE (SAL >= 500 OR SAL <= 3000)
AND COMM IS NOT NULL;

-- 5
SELECT
	EMPNO, ENAME, HIREDATE
FROM emp
WHERE ENAME LIKE '%기' OR ENAME LIKE '%김%'
ORDER BY EMPNO DESC;

-- 6	
SELECT
	EMPNO, ENAME, DEPTNO
	, CASE
      WHEN DEPTNO=10 THEN '인사부'
      WHEN DEPTNO=20 THEN '영업부'
      WHEN DEPTNO=30 THEN '개발부'
      ELSE '생산부'
      END AS DNAME
FROM emp;

-- 7
SELECT EMPNO
	, ENAME
	, HIREDATE
	, IFNULL(COMM,0) AS COMM
FROM EMP
WHERE DATE_FORMAT(HIREDATE, '%m') = 01
ORDER BY HIREDATE ASC;

-- 8
SELECT
	SUM(SAL)
	, AVG(SAL)
	, AVG(COMM)
FROM EMP
GROUP BY DEPTNO
ORDER BY SUM(SAL) DESC;

-- 9
SELECT
	EMPNO
	, ENAME
	, HIREDATE
	, SAL
	, DEPTNO
	, (SELECT DNAME FROM dept WHERE DEPTNO = emp.DEPTNO) DNAME
FROM emp
WHERE DEPTNO = (SELECT DEPTNO FROM dept WHERE DNAME = '인사부');

-- 10
SELECT
	EMPNO
	, ENAME
	, HIREDATE
	, SAL
	, EMP.DEPTNO
	, DNAME
FROM emp
INNER JOIN dept
ON emp.DEPTNO = dept.DEPTNO
WHERE DNAME != '인사부' AND SAL >= 500
ORDER BY EMPNO DESC, ENAME ASC;